### ISSUE TITLE
Discord server invite link has expired

### ISSUE THREAD

**Issue by caniko** [bonsai-rx/bonsai-rx.github.io#2]
This is the link on the [website](https://bonsai-rx.org/community/): https://discord.gg/Cp8ZfQ9ytp, I suggest making an indefinite link and hope that nobody abuses it.

**Comment by glopesdev** [comment]
Thanks for the heads-up, for now I will change the link limit so it expires after X uses, rather than a time limit. That should be easier to control than a time limit.

**Comment by caniko** [comment]
Wow, didn't know that feature existed. Awesome
